### ISSUE TITLE
Windows 8 Support

### ISSUE THREAD

**Issue by garethrepton** [carlospuk/remotepotato#7]
I've been experimenting with Windows 8 and Remote Potato and when it tries to load channels its crashing with the error:

Could not load file or assembly mcstoredb, Version=6.1.0.0 or one of its dependencies. An attempt was made to load a program with an incorrect format.

It looks like Windows 8 has a new version of this dll (6.2.9200), so I guess it may just be a case of rebuilding on Windows 8, at least to get around this problem.

**Comment by garethrepton** [comment]
I have compiled a version on Windows 8 and can confirm that it works correctly as an application on there.

**Comment by carlospuk** [comment]
Hi all
The file you need to re-compile for Win8 support is MSEPG.dll. 

I finally have a Windows 8 build environment with Media Center and have re-compiled this file and confirm that it gets Remote Potato Server fully working again under Windows 8. 

I've uploaded it to the main Remote Potato website - so if you need to grab a copy you can do so from the main downloads page at www.remotepotato.com

If anybody needs me to compile anything under Windows 8, let me know - I have limited time but am happy to do occasional compiles of new code.

Carlos

**Comment by paulspellr** [comment]
**EDIT: Ignore me - an uninstall and clean install of Remote Potato server has fixed the below problem!**

I've just upgraded to Windows 8 and found RemotePotato no longer worked - the server appeared to be running fine in the settings tool but I couldn't connect to it from anywhere. So I found out about and downloaded the MSEPG.dll replacement file and put that in place, which I guess should have fixed that problem - but now I cannot start RemotePotatoUI.exe at all, so can't start the server! RemotePotatoUI.exe gives the error below when it starts initialising. Can anyone suggest what I need to do? Thanks in advance...

```
Unhandled exception has occurred in your application. If you click Continue,
the application will ignore this error and attempt to continue. If you click Quit,
the application will close immediately.

Could not load file or assembly 'CommonEPG, Version=1.8.0.0,
Culture=neutral, PublicKeyToken=a565e5d516736739' or one of its
dependencies. The locatied assembly's manifest definition does not
match the assembly reference. (Exception from HRESULT: 0x80131040).

Details:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileLoadException: Could not load file or assembly 'CommonEPG, Version=1.8.0.0, Culture=neutral, PublicKeyToken=a565e5d516736739' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'CommonEPG, Version=1.8.0.0, Culture=neutral, PublicKeyToken=a565e5d516736739'
   at RemotePotatoServer.EPGManager.ExternalPopulateTVChannels(Boolean skipCache)
   at RemotePotatoServer.Form1.PopulateFormControls()
   at RemotePotatoServer.Form1.Form1_Shown_1(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Form.CallShownEvent()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].



************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18033 built by: FX45RTMGDR
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
RemotePotatoUI
    Assembly Version: 1.3.0.0
    Win32 Version: 1.3.0.0
    CodeBase: file:///C:/Program%20Files/Remote%20Potato/RemotePotatoUI.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18033 built by: FX45RTMGDR
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18022 built by: FX45RTMGDR
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18033 built by: FX45RTMGDR
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
RPServer
    Assembly Version: 2.333.2.0
    Win32 Version: 2.333.2.0
    CodeBase: file:///C:/Program%20Files/Remote%20Potato/RPServer.DLL
----------------------------------------
RemotePotatoSettings
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/Remote%20Potato/RemotePotatoSettings.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18033 built by: FX45RTMGDR
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MSEPG
    Assembly Version: 3.2.2.0
    Win32 Version: 3.2.2.0
    CodeBase: file:///C:/Program%20Files/Remote%20Potato/MSEPG.DLL
----------------------------------------
CommonEPG
    Assembly Version: 1.8.0.0
    Win32 Version: 1.8.0.0
    CodeBase: file:///C:/Program%20Files/Remote%20Potato/CommonEPG.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.0.30319.18033 built by: FX45RTMGDR
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.ServiceProcess
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceProcess/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.ServiceProcess.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by carlospuk** [comment]
I would uninstall and start with a new installation of Remote Potato if I were you. The downloadble msepg dll is only meant to be used with the most recent version of the server.
